import { headers } from "../config/headers.js";

export const harDashboard = [
  ["GET", "https://berrybenka.api.useinsider.com/ins.js?id=10001267", headers],
  [
    "GET",
    "https://berrybenka.api.useinsider.com/views/push/manifest/",
    headers,
  ],
  ["GET", "https://berrybenka.com/", headers],
  ["GET", "https://berrybenka.com/berrybenka/desktop/css/chat.css", headers],
  [
    "GET",
    "https://berrybenka.com/berrybenka/desktop/css/core.css?t=20231010162827",
    headers,
  ],
  [
    "GET",
    "https://berrybenka.com/berrybenka/desktop/css/font-awesome.min.css",
    headers,
  ],
  ["GET", "https://berrybenka.com/berrybenka/desktop/css/home.css", headers],
  [
    "GET",
    "https://berrybenka.com/berrybenka/desktop/css/jquery.fancybox.css",
    headers,
  ],
  [
    "GET",
    "https://berrybenka.com/berrybenka/desktop/css/jqueryui.css",
    headers,
  ],
  ["GET", "https://berrybenka.com/berrybenka/desktop/css/pl.css", headers],
  ["GET", "https://berrybenka.com/berrybenka/desktop/css/reset.css", headers],
  [
    "GET",
    "https://berrybenka.com/berrybenka/desktop/css/search.css?t=20231010162827",
    headers,
  ],
  [
    "GET",
    "https://berrybenka.com/berrybenka/desktop/flexslider/flexslider.css",
    headers,
  ],
  [
    "GET",
    "https://berrybenka.com/berrybenka/desktop/flexslider/fonts/flexslider-icon.woff",
    headers,
  ],
  [
    "GET",
    "https://berrybenka.com/berrybenka/desktop/flexslider/jquery.flexslider.js",
    headers,
  ],
  [
    "GET",
    "https://berrybenka.com/berrybenka/desktop/fonts/fontawesome-webfont.woff2?v=4.5.0",
    headers,
  ],
  [
    "GET",
    "https://berrybenka.com/berrybenka/desktop/fonts/futura.woff",
    headers,
  ],
  [
    "GET",
    "https://berrybenka.com/berrybenka/desktop/fonts/futurabold.woff",
    headers,
  ],
  [
    "GET",
    "https://berrybenka.com/berrybenka/desktop/img/apps-button-android.png",
    headers,
  ],
  [
    "GET",
    "https://berrybenka.com/berrybenka/desktop/img/apps-button-ios.png",
    headers,
  ],
  [
    "GET",
    "https://berrybenka.com/berrybenka/desktop/img/berrybenka-white.png",
    headers,
  ],
  [
    "GET",
    "https://berrybenka.com/berrybenka/desktop/img/berrybenka.png",
    headers,
  ],
  [
    "GET",
    "https://berrybenka.com/berrybenka/desktop/img/bgPattern.png",
    headers,
  ],
  ["GET", "https://berrybenka.com/berrybenka/desktop/img/favicon.png", headers],
  [
    "GET",
    "https://berrybenka.com/berrybenka/desktop/img/icon/rupiah.svg",
    headers,
  ],
  [
    "GET",
    "https://berrybenka.com/berrybenka/desktop/img/icon/truck.svg",
    headers,
  ],
  [
    "GET",
    "https://berrybenka.com/berrybenka/desktop/script/autocomplete.js?t=20231010162827",
    headers,
  ],
  [
    "GET",
    "https://berrybenka.com/berrybenka/desktop/script/clipboard/clipboard.min.js",
    headers,
  ],
  [
    "GET",
    "https://berrybenka.com/berrybenka/desktop/script/core.js?t=20231010162827",
    headers,
  ],
  [
    "GET",
    "https://berrybenka.com/berrybenka/desktop/script/fancybox/jquery.fancybox.css",
    headers,
  ],
  [
    "GET",
    "https://berrybenka.com/berrybenka/desktop/script/fancybox/jquery.fancybox.pack.js",
    headers,
  ],
  [
    "GET",
    "https://berrybenka.com/berrybenka/desktop/script/lazyload.js",
    headers,
  ],
  [
    "GET",
    "https://berrybenka.com/berrybenka/desktop/script/scrollable/jquery.scrollable.css",
    headers,
  ],
  [
    "GET",
    "https://berrybenka.com/berrybenka/desktop/script/scrollable/jquery.scrollable.js",
    headers,
  ],
  [
    "GET",
    "https://berrybenka.com/berrybenka/desktop/script/sticky-side.js",
    headers,
  ],
  [
    "GET",
    "https://berrybenka.com/berrybenka/desktop/script/sticky.js",
    headers,
  ],
  [
    "GET",
    "https://berrybenka.com/js/desktop/app_bb.js?t=20231010162827",
    headers,
  ],
  ["GET", "https://berrybenka.com/js/jquery-1.10.2.js", headers],
  ["GET", "https://berrybenka.com/js/jquery-ui.js", headers],
  [
    "GET",
    "https://berrybenka.com/js/marketing-js/global.js?t=20231010162827",
    headers,
  ],
];
